/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bank.Bank;
import connection.MySql;
import connection.forex;
import connection.telegram;
import java.awt.Color;
import java.awt.Component;
import java.awt.Event;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import models.Customer;


/**
 *
 * @author roboto
 */
public class Customer_view extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    
    
    Connection conn;
    Object[] accounts;
    private int mousex;
    private int mousey;
            
    public Customer_view() throws SQLException, Exception {
        initComponents();
        if(!Bank.isLoggedIn()){
            Login_view lv = new Login_view();
            this.hide();
            lv.setVisible(true);
        }        
        conn = MySql.getConnection();
        FirstNameTextField.setText(Customer.getFirstName());
        LastNameLabel.setText(Customer.getLastName());
        EmailTextField.setText(Customer.getEmail());
        PhoneNumberTextField.setText(Customer.getPhone());
        PasswordField.setText(Customer.getPassword());
        try {
            jTextField1.setText(Customer.getTelegramId(Bank.authenticatedUserId));
        } catch (SQLException ex) {
            Bank.showError("SQL Error");
        }
        String DOB = Customer.getDate();
        PreparedStatement ps = conn.prepareStatement("Select * from Transaction where sender = ? or recipient = ?");
        ps.setInt(1, Bank.selectedAccountNumber);   
        ps.setInt(2, Bank.selectedAccountNumber);        
        ResultSet rs = ps.executeQuery();
        resultSetToTableModel(rs, Transactions);
        ps.close();
        accounts = getAccounts().toArray();
        selectAccount.addItem("-----");
        for(int i=0;i<accounts.length;i++)
        {
            selectAccount.addItem((String) accounts[i]);
        }
//        currentBalance.setText(Integer.toString(Bank.selectedAccountNumber));
        selectedAccNum();
        ArrayList<Double> rates = forex.getRates();
        ETBRate.setText(String.valueOf(rates.get(0)));
        USDRate.setText(String.valueOf(rates.get(1)));
        JPYRate.setText(String.valueOf(rates.get(2)));
        GBPRate.setText(String.valueOf(rates.get(3)));       
        
    }
    public ArrayList getAccounts() throws SQLException{
        ArrayList<String> accounts = new ArrayList<String>();
//        PreparedStatement ps;
//        ps = conn.prepareStatement("select * from Account where owner = ?");
//        ps.setInt(1, Bank.authenticatedUserId);
//        ResultSet rs = ps.executeQuery();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("select * from Account where owner = " + Bank.authenticatedUserId);
        
        while(rs.next()){
               accounts.add(rs.getString("account_number"));              
        }
        return accounts;
    }
    public static void resultSetToTableModel(ResultSet rs, JTable table) throws SQLException{
        DefaultTableModel tableModel = new DefaultTableModel();

        ResultSetMetaData metaData = rs.getMetaData();

        int columnCount = metaData.getColumnCount();

        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++){
            tableModel.addColumn(metaData.getColumnLabel(columnIndex));
        }

        Object[] row = new Object[columnCount];
        while (rs.next()){
            for (int i = 0; i < columnCount; i++){
                row[i] = rs.getObject(i+1);
            }
            tableModel.addRow(row);
        }
        table.setModel(tableModel);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        accountTab = new javax.swing.JPanel();
        selectAccount = new javax.swing.JComboBox<>();
        addAccountButton = new javax.swing.JLabel();
        selectAccountLabel = new javax.swing.JLabel();
        balancePanel1 = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        balancePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ETBRate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        USDRate = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JPYRate = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        GBPRate = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectedAccountLabel = new javax.swing.JLabel();
        transactionSummaryPanel = new javax.swing.JPanel();
        transactionSummaryLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        summaryReport = new javax.swing.JTable();
        removeAccountButton = new javax.swing.JLabel();
        transferTab = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        transferAmount = new javax.swing.JTextField();
        transferAccountNumber = new javax.swing.JTextField();
        transferButton = new keeptoo.KButton();
        amountSep = new javax.swing.JSeparator();
        accountSep = new javax.swing.JSeparator();
        settingsTab = new javax.swing.JScrollPane();
        MainRegisterPanel = new javax.swing.JPanel();
        RegisterLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        PhoneNumberTextField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        kButton1 = new keeptoo.KButton();
        reportTab = new javax.swing.JScrollPane();
        Transactions = new javax.swing.JTable();
        logoutTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        transferButton1 = new keeptoo.KButton();
        transferButton2 = new keeptoo.KButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(219, 216, 227));
        setUndecorated(true);

        TabbedPane.setBackground(new java.awt.Color(49, 49, 49));
        TabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        TabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabbedPane.setToolTipText("");
        TabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabbedPane.setFont(new java.awt.Font("Montserrat Light", 1, 12)); // NOI18N
        TabbedPane.setName(""); // NOI18N
        TabbedPane.setPreferredSize(new java.awt.Dimension(800, 600));
        TabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneStateChanged(evt);
            }
        });
        TabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabbedPaneMouseClicked(evt);
            }
        });

        accountTab.setBackground(new java.awt.Color(82, 82, 82));
        accountTab.setForeground(new java.awt.Color(255, 255, 255));
        accountTab.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        selectAccount.setBackground(new java.awt.Color(102, 102, 102));
        selectAccount.setForeground(new java.awt.Color(255, 255, 255));
        selectAccount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectAccountItemStateChanged(evt);
            }
        });
        selectAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAccountActionPerformed(evt);
            }
        });

        addAccountButton.setBackground(new java.awt.Color(0, 255, 255));
        addAccountButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        addAccountButton.setText("+");
        addAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAccountButtonMouseClicked(evt);
            }
        });

        selectAccountLabel.setFont(new java.awt.Font("Montserrat Light", 1, 12)); // NOI18N
        selectAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectAccountLabel.setText("Change Active Account");

        balancePanel1.setBackground(new java.awt.Color(49, 49, 49));

        balanceLabel.setFont(new java.awt.Font("Gravity Light", 1, 24)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceLabel.setText("-----");

        jLabel11.setFont(new java.awt.Font("Montserrat Light", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Current Balance");

        javax.swing.GroupLayout balancePanel1Layout = new javax.swing.GroupLayout(balancePanel1);
        balancePanel1.setLayout(balancePanel1Layout);
        balancePanel1Layout.setHorizontalGroup(
            balancePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addGroup(balancePanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        balancePanel1Layout.setVerticalGroup(
            balancePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balancePanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        balancePanel.setBackground(new java.awt.Color(49, 49, 49));
        balancePanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(49, 49, 49));
        jLabel6.setFont(new java.awt.Font("Montserrat Light", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Foreign Exchange Rates");

        jLabel9.setBackground(new java.awt.Color(49, 49, 49));
        jLabel9.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("1");

        jLabel10.setBackground(new java.awt.Color(49, 49, 49));
        jLabel10.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EUR");

        jLabel12.setBackground(new java.awt.Color(49, 49, 49));
        jLabel12.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ETB");

        ETBRate.setBackground(new java.awt.Color(49, 49, 49));
        ETBRate.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        ETBRate.setForeground(new java.awt.Color(255, 255, 255));
        ETBRate.setText("jLabel9");

        jLabel14.setBackground(new java.awt.Color(49, 49, 49));
        jLabel14.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("1");

        jLabel15.setBackground(new java.awt.Color(49, 49, 49));
        jLabel15.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EUR");

        USDRate.setBackground(new java.awt.Color(49, 49, 49));
        USDRate.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        USDRate.setForeground(new java.awt.Color(255, 255, 255));
        USDRate.setText("jLabel9");

        jLabel17.setBackground(new java.awt.Color(49, 49, 49));
        jLabel17.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("USD");

        jLabel18.setBackground(new java.awt.Color(49, 49, 49));
        jLabel18.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("1");

        jLabel19.setBackground(new java.awt.Color(49, 49, 49));
        jLabel19.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("EUR");

        JPYRate.setBackground(new java.awt.Color(49, 49, 49));
        JPYRate.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        JPYRate.setForeground(new java.awt.Color(255, 255, 255));
        JPYRate.setText("jLabel9");

        jLabel21.setBackground(new java.awt.Color(49, 49, 49));
        jLabel21.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("JPY");

        jLabel20.setBackground(new java.awt.Color(49, 49, 49));
        jLabel20.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("1");

        jLabel22.setBackground(new java.awt.Color(49, 49, 49));
        jLabel22.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("EUR");

        GBPRate.setBackground(new java.awt.Color(49, 49, 49));
        GBPRate.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        GBPRate.setForeground(new java.awt.Color(255, 255, 255));
        GBPRate.setText("jLabel9");

        jLabel23.setBackground(new java.awt.Color(49, 49, 49));
        jLabel23.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("GBP");

        javax.swing.GroupLayout balancePanelLayout = new javax.swing.GroupLayout(balancePanel);
        balancePanel.setLayout(balancePanelLayout);
        balancePanelLayout.setHorizontalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balancePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, balancePanelLayout.createSequentialGroup()
                        .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel22)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, balancePanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, balancePanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balancePanelLayout.createSequentialGroup()
                        .addComponent(JPYRate)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balancePanelLayout.createSequentialGroup()
                        .addComponent(GBPRate)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balancePanelLayout.createSequentialGroup()
                        .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ETBRate)
                            .addComponent(USDRate))
                        .addGap(18, 18, 18)
                        .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
            .addGroup(balancePanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        balancePanelLayout.setVerticalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ETBRate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USDRate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balancePanelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(balancePanelLayout.createSequentialGroup()
                        .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPYRate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GBPRate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        jLabel2.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selected Account: ");

        selectedAccountLabel.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        selectedAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectedAccountLabel.setText("-------");

        transactionSummaryPanel.setBackground(new java.awt.Color(49, 49, 49));

        transactionSummaryLabel.setFont(new java.awt.Font("Gravity Book", 1, 14)); // NOI18N
        transactionSummaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        transactionSummaryLabel.setText("Transactions Summary");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        summaryReport.setBackground(new java.awt.Color(153, 153, 153));
        summaryReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        summaryReport.setGridColor(new java.awt.Color(153, 153, 153));
        summaryReport.setRowHeight(30);
        summaryReport.getTableHeader().setResizingAllowed(false);
        summaryReport.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(summaryReport);

        javax.swing.GroupLayout transactionSummaryPanelLayout = new javax.swing.GroupLayout(transactionSummaryPanel);
        transactionSummaryPanel.setLayout(transactionSummaryPanelLayout);
        transactionSummaryPanelLayout.setHorizontalGroup(
            transactionSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionSummaryPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(transactionSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionSummaryPanelLayout.createSequentialGroup()
                        .addComponent(transactionSummaryLabel)
                        .addGap(0, 659, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        transactionSummaryPanelLayout.setVerticalGroup(
            transactionSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionSummaryPanelLayout.createSequentialGroup()
                .addComponent(transactionSummaryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        removeAccountButton.setBackground(new java.awt.Color(0, 255, 255));
        removeAccountButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        removeAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        removeAccountButton.setText("-");
        removeAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeAccountButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout accountTabLayout = new javax.swing.GroupLayout(accountTab);
        accountTab.setLayout(accountTabLayout);
        accountTabLayout.setHorizontalGroup(
            accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountTabLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountTabLayout.createSequentialGroup()
                        .addComponent(transactionSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountTabLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(accountTabLayout.createSequentialGroup()
                                .addComponent(balancePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(balancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(accountTabLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectedAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selectAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addGap(76, 76, 76))))
        );
        accountTabLayout.setVerticalGroup(
            accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountTabLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selectedAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectAccountLabel)
                        .addComponent(addAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(removeAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balancePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(transactionSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("Account", new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/Users-User-Male-4-icon.png"), accountTab); // NOI18N

        transferTab.setBackground(new java.awt.Color(82, 82, 82));
        transferTab.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBackground(new java.awt.Color(49, 49, 49));

        jPanel11.setBackground(new java.awt.Color(49, 49, 49));

        transferAmount.setBackground(new java.awt.Color(49, 49, 49));
        transferAmount.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        transferAmount.setForeground(new java.awt.Color(255, 255, 255));
        transferAmount.setText("Enter Amount");
        transferAmount.setBorder(null);
        transferAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                transferAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                transferAmountFocusLost(evt);
            }
        });
        transferAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAmountActionPerformed(evt);
            }
        });

        transferAccountNumber.setBackground(new java.awt.Color(49, 49, 49));
        transferAccountNumber.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        transferAccountNumber.setForeground(new java.awt.Color(255, 255, 255));
        transferAccountNumber.setText("Enter Account Number");
        transferAccountNumber.setBorder(null);
        transferAccountNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                transferAccountNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                transferAccountNumberFocusLost(evt);
            }
        });
        transferAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAccountNumberActionPerformed(evt);
            }
        });

        transferButton.setBorder(null);
        transferButton.setText("TRANSFER");
        transferButton.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        transferButton.setkAllowTab(false);
        transferButton.setkBackGroundColor(new java.awt.Color(202, 62, 71));
        transferButton.setkEndColor(new java.awt.Color(202, 62, 71));
        transferButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        transferButton.setkHoverForeGround(new java.awt.Color(202, 62, 71));
        transferButton.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        transferButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        transferButton.setkStartColor(new java.awt.Color(202, 62, 71));
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(transferAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountSep, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountSep, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(transferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(transferAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        transferTab.add(jPanel6, new java.awt.GridBagConstraints());

        TabbedPane.addTab("Transfer", new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/407799-200.png"), transferTab); // NOI18N

        settingsTab.setBorder(null);
        settingsTab.setToolTipText("");

        MainRegisterPanel.setBackground(new java.awt.Color(51, 51, 51));

        RegisterLabel.setFont(new java.awt.Font("Montserrat Light", 1, 18)); // NOI18N
        RegisterLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegisterLabel.setText("Update Account Info");

        FirstNameTextField.setBackground(new java.awt.Color(82, 82, 82));
        FirstNameTextField.setFont(new java.awt.Font("Montserrat Light", 1, 12)); // NOI18N
        FirstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameTextField.setText("First name");
        FirstNameTextField.setBorder(null);

        LastNameLabel.setBackground(new java.awt.Color(82, 82, 82));
        LastNameLabel.setFont(new java.awt.Font("Montserrat Light", 1, 12)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        LastNameLabel.setText("Last name");
        LastNameLabel.setBorder(null);

        EmailTextField.setBackground(new java.awt.Color(82, 82, 82));
        EmailTextField.setFont(new java.awt.Font("Montserrat Light", 1, 12)); // NOI18N
        EmailTextField.setForeground(new java.awt.Color(255, 255, 255));
        EmailTextField.setText("Email Address");
        EmailTextField.setBorder(null);

        PhoneNumberTextField.setBackground(new java.awt.Color(82, 82, 82));
        PhoneNumberTextField.setFont(new java.awt.Font("Montserrat Light", 1, 12)); // NOI18N
        PhoneNumberTextField.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberTextField.setText("Phone Number");
        PhoneNumberTextField.setBorder(null);

        updateButton.setFont(new java.awt.Font("Gravity Book", 1, 12)); // NOI18N
        updateButton.setText("Update");
        updateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        PasswordField.setBackground(new java.awt.Color(82, 82, 82));
        PasswordField.setFont(new java.awt.Font("Montserrat Light", 1, 12)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField.setText("Password");
        PasswordField.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telegram Account");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(82, 82, 82));
        jTextField1.setText(" ");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Gravity", 1, 12)); // NOI18N
        jButton2.setText("Connect");

        kButton1.setBackground(new java.awt.Color(255, 0, 51));
        kButton1.setForeground(new java.awt.Color(255, 0, 51));
        kButton1.setText("Delete User Account");
        kButton1.setkFillButton(false);
        kButton1.setkForeGround(new java.awt.Color(255, 0, 51));
        kButton1.setkHoverColor(new java.awt.Color(255, 0, 51));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 0, 51));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 0, 51));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 0, 51));
        kButton1.setkPressedColor(new java.awt.Color(255, 0, 51));
        kButton1.setkSelectedColor(new java.awt.Color(255, 0, 51));
        kButton1.setkStartColor(new java.awt.Color(255, 0, 51));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainRegisterPanelLayout = new javax.swing.GroupLayout(MainRegisterPanel);
        MainRegisterPanel.setLayout(MainRegisterPanelLayout);
        MainRegisterPanelLayout.setHorizontalGroup(
            MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainRegisterPanelLayout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383))
            .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(RegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainRegisterPanelLayout.setVerticalGroup(
            MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(RegisterLabel)
                .addGap(18, 18, 18)
                .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addGap(20, 20, 20)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        settingsTab.setViewportView(MainRegisterPanel);

        TabbedPane.addTab("Settings", new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/Windows_Settings_app_icon.png"), settingsTab); // NOI18N

        reportTab.setBackground(new java.awt.Color(82, 82, 82));

        Transactions.setBackground(new java.awt.Color(153, 153, 153));
        Transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Transactions.setRowHeight(35);
        reportTab.setViewportView(Transactions);

        TabbedPane.addTab("Report", new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/transact.png"), reportTab); // NOI18N

        logoutTab.setBackground(new java.awt.Color(82, 82, 82));
        logoutTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutTabMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat Thin", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Are you sure you want to logout?");

        transferButton1.setBorder(null);
        transferButton1.setText("No");
        transferButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        transferButton1.setkAllowTab(false);
        transferButton1.setkBackGroundColor(new java.awt.Color(202, 62, 71));
        transferButton1.setkEndColor(new java.awt.Color(202, 62, 71));
        transferButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        transferButton1.setkHoverForeGround(new java.awt.Color(202, 62, 71));
        transferButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        transferButton1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        transferButton1.setkStartColor(new java.awt.Color(202, 62, 71));
        transferButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButton1LoginButtonActionPerformed(evt);
            }
        });

        transferButton2.setBorder(null);
        transferButton2.setText("Yes");
        transferButton2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        transferButton2.setkAllowTab(false);
        transferButton2.setkBackGroundColor(new java.awt.Color(202, 62, 71));
        transferButton2.setkEndColor(new java.awt.Color(202, 62, 71));
        transferButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        transferButton2.setkHoverForeGround(new java.awt.Color(202, 62, 71));
        transferButton2.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        transferButton2.setkSelectedColor(new java.awt.Color(255, 255, 255));
        transferButton2.setkStartColor(new java.awt.Color(202, 62, 71));
        transferButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButton2LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoutTabLayout = new javax.swing.GroupLayout(logoutTab);
        logoutTab.setLayout(logoutTabLayout);
        logoutTabLayout.setHorizontalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutTabLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transferButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(transferButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );
        logoutTabLayout.setVerticalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutTabLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );

        TabbedPane.addTab(" Logout", new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/logout.png"), logoutTab); // NOI18N

        jPanel2.setBackground(new java.awt.Color(49, 49, 49));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(49, 49, 49));

        jLabel8.setFont(new java.awt.Font("Montserrat Thin", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Welcome to Commercial Ethiopian Bank");

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/close.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void selectedAccNum(){
        try {
            Bank.selectedAccountNumber = Integer.parseInt((String) selectAccount.getSelectedItem());
            selectAccount.removeAllItems();
            selectAccount.addItem("------");
            accounts = getAccounts().toArray();
            for(int i=0;i<accounts.length;i++)
            {
                selectAccount.addItem((String) accounts[i]);
                
            }
            selectAccount.setSelectedItem(Bank.selectedAccountNumber);
            selectedAccountLabel.setText(String.valueOf(Bank.selectedAccountNumber));
            NumberFormat format = NumberFormat.getCurrencyInstance();
            balanceLabel.setText(format.format(Customer.getBalance(Bank.selectedAccountNumber)));
            Connection conn = MySql.getConnection();
            PreparedStatement ps = conn.prepareStatement("Select transaction_id as ID, Sender as 'Account Number', amount as 'Amount', time as Time from Transaction where sender = ? or recipient = ? ORDER BY time DESC limit 5");
            ps.setInt(1, Bank.selectedAccountNumber);
            ps.setInt(2, Bank.selectedAccountNumber);
            ResultSet rs = ps.executeQuery();
            resultSetToTableModel(rs, summaryReport);
//            currentBalance.setText(Integer.toString(Bank.selectedAccountNumber));
        } catch (SQLException ex) {
            Logger.getLogger(Customer_view.class.getName()).log(Level.SEVERE, null, ex);
        } catch (java.lang.NumberFormatException ex){
            
        }
    }
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        this.mousex = evt.getX();
        this.mousey = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(evt.getXOnScreen() - mousex , evt.getYOnScreen() - mousey);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setIcon(new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/close_hover.png"));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setIcon(new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/close.png"));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void TabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneMouseClicked

    private void TabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneStateChanged
        try {
            Connection conn = MySql.getConnection();
            PreparedStatement ps = conn.prepareStatement("Select * from Transaction where sender = ? or recipient = ?");
            ps.setInt(1, Bank.selectedAccountNumber);
            ps.setInt(2, Bank.selectedAccountNumber);
            ResultSet rs = ps.executeQuery();
            resultSetToTableModel(rs, Transactions);
            ps.close();
        } catch (SQLException ex) {
            Bank.showError("SQL Error");
        }
        getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_TabbedPaneStateChanged

    private void logoutTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutTabMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutTabMouseClicked

    private void transferButton2LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButton2LoginButtonActionPerformed
        Login_view lv = new Login_view();
        this.hide();
        lv.setVisible(true);
    }//GEN-LAST:event_transferButton2LoginButtonActionPerformed

    private void transferButton1LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButton1LoginButtonActionPerformed
        TabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_transferButton1LoginButtonActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "You are about to delete your User Account. Are you absolutely sure?");
        if(x==0)
        {
            Customer.delete(Bank.authenticatedUserId);
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            String fName = FirstNameTextField.getText().isEmpty() ? Customer.getFirstName() : FirstNameTextField.getText();
            String lName = LastNameLabel.getText().isEmpty() ? Customer.getFirstName() : LastNameLabel.getText();
            String phone = PhoneNumberTextField.getText().isEmpty() ? Customer.getFirstName() : PhoneNumberTextField.getText();
            String email = EmailTextField.getText().isEmpty() ? Customer.getFirstName() : EmailTextField.getText();
            String password = PasswordField.getText().isEmpty() ? Customer.getFirstName() : PasswordField.getText();
            
            Customer.updateCustomer(fName, lName, email, phone, Customer.getUsername(), password);
            
        } catch (SQLException ex) {
            ex.printStackTrace();
            Bank.showError("SQL error");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void transferButtonLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonLoginButtonActionPerformed
        try{

            int transferVal = Integer.parseInt(transferAmount.getText());
            int transferAccNum = Integer.parseInt(transferAccountNumber.getText());
            int balance = 0;
            balance = Customer.getBalance(Bank.selectedAccountNumber);
            System.out.println(balance+ " " + transferVal + " " + transferAccNum + " " +Bank.selectedAccountNumber);
            if(transferVal<10){
                Bank.showError("Requested Transfer amount is less than minimun value.");
                return;
            } else if(transferVal>balance){
                Bank.showError("Requested Transfer amount is more than your current balance.");
                return;
            }

            Customer.Transfer(transferVal, Bank.selectedAccountNumber, transferAccNum);
            Bank.showError("Please fill both field before submitting");
        }catch(Exception ex)
        {
            Bank.showError("Internal Error");
        }
    }//GEN-LAST:event_transferButtonLoginButtonActionPerformed

    private void transferAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAccountNumberActionPerformed

    private void transferAccountNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transferAccountNumberFocusLost
        // TODO add your handling code here:
        if(transferAccountNumber.getText().isEmpty()){
            transferAccountNumber.setText("Enter Account Number");
        }
    }//GEN-LAST:event_transferAccountNumberFocusLost

    private void transferAccountNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transferAccountNumberFocusGained
        if(transferAccountNumber.getText().equals("Enter Account Number"))
        {
            transferAccountNumber.setText("");
        }
    }//GEN-LAST:event_transferAccountNumberFocusGained

    private void transferAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmountActionPerformed

    private void transferAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transferAmountFocusLost
        // TODO add your handling code here:
        if(transferAmount.getText().isEmpty()){
            transferAmount.setText("Enter Amount");
        }
    }//GEN-LAST:event_transferAmountFocusLost

    private void transferAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transferAmountFocusGained
        // TODO add your handling code here:
        if(transferAmount.getText().equals("Enter Amount")){
            transferAmount.setText("");
        }
    }//GEN-LAST:event_transferAmountFocusGained

    private void addAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAccountButtonMouseClicked

        int is_interestable = JOptionPane.showConfirmDialog((Component)this,"Do you want this account to be interestable?" ,"Title", JOptionPane.YES_NO_CANCEL_OPTION);
        if(is_interestable==2)
        {
            return;
        }
        int ret = JOptionPane.showConfirmDialog((Component)this,"You are about to create a new account. Are you sure you want to continue?","Add account", JOptionPane.YES_NO_OPTION);
        if(ret != 0)
        {
            return;
        }
        try {
            Customer.createAccount(Bank.authenticatedUserId,is_interestable);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_addAccountButtonMouseClicked

    private void selectAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAccountActionPerformed

        selectedAccNum();
    }//GEN-LAST:event_selectAccountActionPerformed

    private void selectAccountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectAccountItemStateChanged

    }//GEN-LAST:event_selectAccountItemStateChanged

    private void removeAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeAccountButtonMouseClicked
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "You are about to delete the selected Account. ARE YOU SURE YOU WANT TO CONTINUE?", "CONFIRM ACCOUNT DELETION" ,JOptionPane.YES_NO_OPTION);
        if(x==0)
            Customer.deleteAccount();
    }//GEN-LAST:event_removeAccountButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void Main_view(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                try {
                    new Customer_view().setVisible(true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                } catch (Exception ex) {
                    Logger.getLogger(Customer_view.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ETBRate;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel GBPRate;
    private javax.swing.JLabel JPYRate;
    private javax.swing.JTextField LastNameLabel;
    private javax.swing.JPanel MainRegisterPanel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTable Transactions;
    private javax.swing.JLabel USDRate;
    private javax.swing.JSeparator accountSep;
    private javax.swing.JPanel accountTab;
    private javax.swing.JLabel addAccountButton;
    private javax.swing.JSeparator amountSep;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JPanel balancePanel;
    private javax.swing.JPanel balancePanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KButton kButton1;
    private javax.swing.JPanel logoutTab;
    private javax.swing.JLabel removeAccountButton;
    private javax.swing.JScrollPane reportTab;
    private javax.swing.JComboBox<String> selectAccount;
    private javax.swing.JLabel selectAccountLabel;
    private javax.swing.JLabel selectedAccountLabel;
    private javax.swing.JScrollPane settingsTab;
    private javax.swing.JTable summaryReport;
    private javax.swing.JLabel transactionSummaryLabel;
    private javax.swing.JPanel transactionSummaryPanel;
    private javax.swing.JTextField transferAccountNumber;
    private javax.swing.JTextField transferAmount;
    private keeptoo.KButton transferButton;
    private keeptoo.KButton transferButton1;
    private keeptoo.KButton transferButton2;
    private javax.swing.JPanel transferTab;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
