/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bank.Bank;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import models.Customer;



/**
 *
 * @author CSEC_Admin
 */
public class Login_view extends javax.swing.JFrame {

    /**
     * Creates new form Login_view
     */
    public Login_view() {
        initComponents();
        MainRegisterPanel.setVisible(false);
        DOBTextField.setText("DD");
        DOBTextField.setForeground(Color.GRAY);
        DOBTextField1.setText("MM");
        DOBTextField1.setForeground(Color.GRAY);
        DOBTextField2.setText("YYYY");
        DOBTextField2.setForeground(Color.GRAY);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interest = new javax.swing.ButtonGroup();
        MainLoginPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pass = new javax.swing.JPasswordField();
        acc_num = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        AccountNumberLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        CreateAccountLabel = new javax.swing.JLabel();
        MainRegisterPanel = new javax.swing.JPanel();
        RegisterLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        EmailAddressLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        PhoneNumberTextField = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        DOBField = new javax.swing.JLabel();
        DOBTextField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        DOBField1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        DOBTextField1 = new javax.swing.JTextField();
        DOBTextField2 = new javax.swing.JTextField();
        Backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        MainLoginPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 190, 20));

        acc_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_numActionPerformed(evt);
            }
        });
        jPanel1.add(acc_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 190, 20));

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 120, 30));

        AccountNumberLabel.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        AccountNumberLabel.setText("Account Number");
        jPanel1.add(AccountNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, 20));

        PasswordLabel.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        PasswordLabel.setText("Password");
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 110, 30));

        CreateAccountLabel.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        CreateAccountLabel.setText("Create account");
        CreateAccountLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateAccountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateAccountLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CreateAccountLabelMouseEntered(evt);
            }
        });
        jPanel1.add(CreateAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 80, 20));

        javax.swing.GroupLayout MainLoginPanelLayout = new javax.swing.GroupLayout(MainLoginPanel);
        MainLoginPanel.setLayout(MainLoginPanelLayout);
        MainLoginPanelLayout.setHorizontalGroup(
            MainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainLoginPanelLayout.setVerticalGroup(
            MainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLoginPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        MainRegisterPanel.setBackground(new java.awt.Color(204, 204, 204));

        RegisterLabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 14)); // NOI18N
        RegisterLabel.setText("Register");

        FirstNameLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        FirstNameLabel.setText("First name");

        LastNameTextField.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        LastNameTextField.setText("Last name");

        EmailAddressLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        EmailAddressLabel.setText("Email Address");

        PhoneNumberLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        PhoneNumberLabel.setText("Phone Number");

        Password.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Password.setText("Password");

        DOBField.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        DOBField.setText("Date of birth");

        DOBTextField.setForeground(Color.GRAY);
        DOBTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBTextFieldFocusLost(evt);
            }
        });

        RegisterButton.setText("Register");
        RegisterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        DOBField1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        DOBField1.setText("Interest-Free");

        interest.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jRadioButton1.setText("Yes");

        interest.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jRadioButton2.setText("No");

        DOBTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBTextField1FocusLost(evt);
            }
        });

        DOBTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBTextField2FocusLost(evt);
            }
        });

        Backbutton.setText("Back");
        Backbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainRegisterPanelLayout = new javax.swing.GroupLayout(MainRegisterPanel);
        MainRegisterPanel.setLayout(MainRegisterPanelLayout);
        MainRegisterPanelLayout.setHorizontalGroup(
            MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addComponent(Password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addComponent(PhoneNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addComponent(EmailAddressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addComponent(LastNameTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FirstNameLabel)
                            .addComponent(RegisterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                        .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DOBField1)
                            .addComponent(DOBField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DOBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DOBTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainRegisterPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1)
                            .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        MainRegisterPanelLayout.setVerticalGroup(
            MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterLabel)
                .addGap(18, 18, 18)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameTextField)
                    .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailAddressLabel)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel)
                    .addComponent(PhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBField)
                    .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBField1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(MainRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLoginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainRegisterPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLoginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainRegisterPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acc_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_numActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        try {
            // TODO add your handling code here:
            onClickLogin();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CreateAccountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountLabelMouseClicked
        // TODO add your handling code here:
//        this.hide();
        MainLoginPanel.setVisible(false);
        MainRegisterPanel.setVisible(true);
    }//GEN-LAST:event_CreateAccountLabelMouseClicked

    private void CreateAccountLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountLabelMouseEntered
        // TODO add your handling code here:
        this.setForeground(Color.blue);
        Font font = this.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        this.setFont(font.deriveFont(attributes));

    }//GEN-LAST:event_CreateAccountLabelMouseEntered

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        try {
            // TODO add your handling code here:
            if(Customer.registerUser(FirstNameTextField.getText(), LastNameLabel.getText(), EmailTextField.getText(), PhoneNumberTextField.getText(), PasswordField.getText(), "Yes".equals(interest.getSelection().getActionCommand()), DOBTextField.getText(),DOBTextField1.getText(),DOBTextField2.getText()))
                JOptionPane.showMessageDialog(this, "You have successfully registered to C.E.B. Please go to our nearest branch and have your initial deposit to activate this account.");
        } catch (ParseException ex) {
            Logger.getLogger(Login_view.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void DOBTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextFieldFocusGained
        // TODO add your handling code here:
        DOBTextField.setText("");
        DOBTextField.setForeground(Color.BLACK);
    }//GEN-LAST:event_DOBTextFieldFocusGained

    private void DOBTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextFieldFocusLost
        // TODO add your handling code here:
        if(DOBTextField.getText().isEmpty()){
            DOBTextField.setText("DD");
            DOBTextField.setForeground(Color.GRAY);
        }
        
    }//GEN-LAST:event_DOBTextFieldFocusLost

    private void DOBTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextField1FocusGained
           // TODO add your handling code here:
           DOBTextField1.setText("");
        DOBTextField1.setForeground(Color.BLACK);
           
    }//GEN-LAST:event_DOBTextField1FocusGained

    private void DOBTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextField1FocusLost
        // TODO add your handling code here:
        if(DOBTextField1.getText().isEmpty()){
            DOBTextField1.setText("MM");
            DOBTextField1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_DOBTextField1FocusLost

    private void DOBTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextField2FocusGained
        // TODO add your handling code here:
        DOBTextField2.setText("");
        DOBTextField2.setForeground(Color.BLACK);
    }//GEN-LAST:event_DOBTextField2FocusGained

    private void DOBTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextField2FocusLost
        // TODO add your handling code here:
        if(DOBTextField2.getText().isEmpty()){
            DOBTextField2.setText("YYYY");
            DOBTextField2.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_DOBTextField2FocusLost

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        // TODO add your handling code here:
        MainRegisterPanel.hide();
        MainLoginPanel.setVisible(true);
    }//GEN-LAST:event_BackbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_view().setVisible(true);
            }
        });
    }
    
    public void onClickLogin() throws SQLException{
        if(this.acc_num.getText().length()==0 || this.pass.getText().length()==0){
            System.out.println("Please input both field");
        }else{
            if (Bank.authenticate(this.acc_num.getText(), this.pass.getText()))
            {
                Main_view main_view = new Main_view();
                main_view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.setVisible(false);
                main_view.setVisible(true);
            }
            else{
                System.out.println("Authentication failed");
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNumberLabel;
    private javax.swing.JButton Backbutton;
    private javax.swing.JLabel CreateAccountLabel;
    private javax.swing.JLabel DOBField;
    private javax.swing.JLabel DOBField1;
    private javax.swing.JTextField DOBTextField;
    private javax.swing.JTextField DOBTextField1;
    private javax.swing.JTextField DOBTextField2;
    private javax.swing.JLabel EmailAddressLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameLabel;
    private javax.swing.JLabel LastNameTextField;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel MainLoginPanel;
    private javax.swing.JPanel MainRegisterPanel;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JTextField acc_num;
    private javax.swing.ButtonGroup interest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
