/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bank.Bank;
import connection.MySql;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.Customer;

/**
 *
 * @author roboto
 */
public class Main_view extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    
    Connection conn;
            
    public Main_view() throws SQLException {
        initComponents();
        if(!Bank.isLoggedIn()){
            Login_view lv = new Login_view();
            this.hide();
            lv.setVisible(true);
        }
        conn = MySql.getConnection();
        FirstNameTextField.setText(Customer.getFirstName());
        LastNameLabel.setText(Customer.getLastName());
        EmailTextField.setText(Customer.getEmail());
        PhoneNumberTextField.setText(Customer.getPhone());
        PasswordField.setText(Customer.getPassword());
        String DOB = Customer.getDate();
        PreparedStatement ps = conn.prepareStatement("Select DISTINCT t.transaction_id, c.first_name, c.last_name,t.amount,tt.type_name  from Transaction as t, Customer as c, Transaction_types as tt where (sender = ? or recipient = ? ) and t.sender = c.account_number");
        ps.setString(1, Bank.authenticatedUser);
        ps.setString(2, Bank.authenticatedUser);        
        ResultSet rs = ps.executeQuery();
        resultSetToTableModel(rs, Transactions);
    }
    public void resultSetToTableModel(ResultSet rs, JTable table) throws SQLException{
        DefaultTableModel tableModel = new DefaultTableModel();

        ResultSetMetaData metaData = rs.getMetaData();

        int columnCount = metaData.getColumnCount();

        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++){
            tableModel.addColumn(metaData.getColumnLabel(columnIndex));
        }

        Object[] row = new Object[columnCount];
        while (rs.next()){
            for (int i = 0; i < columnCount; i++){
                row[i] = rs.getObject(i+1);
            }
            tableModel.addRow(row);
        }
        table.setModel(tableModel);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        depositButton = new javax.swing.JButton();
        depositBox = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        withdrawalBox = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        transferAmount = new javax.swing.JTextField();
        transferButton = new javax.swing.JButton();
        transferAccountNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MainRegisterPanel = new javax.swing.JPanel();
        RegisterLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        EmailAddressLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        PhoneNumberTextField = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        DOBField = new javax.swing.JLabel();
        DOBTextField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        interestLabel = new javax.swing.JLabel();
        yesButton = new javax.swing.JRadioButton();
        noButton = new javax.swing.JRadioButton();
        DOBTextField1 = new javax.swing.JTextField();
        DOBTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Transactions = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogoutYes = new javax.swing.JButton();
        LogoutNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabbedPane.setToolTipText("");
        TabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabbedPane.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        TabbedPane.setName(""); // NOI18N
        TabbedPane.setPreferredSize(new java.awt.Dimension(800, 600));
        TabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabbedPaneMouseClicked(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Enter the amount you want to Deposit");

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(depositBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(depositButton)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(depositBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(depositButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel7, new java.awt.GridBagConstraints());

        TabbedPane.addTab("Deposit", new javax.swing.ImageIcon(getClass().getResource("/10-512.png")), jPanel1); // NOI18N
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Enter the amount you want to Withdraw");

        jButton2.setText("Withdraw");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(withdrawalBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(withdrawalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        jPanel2.add(jPanel5, gridBagConstraints);

        TabbedPane.addTab("Withdraw", new javax.swing.ImageIcon(getClass().getResource("/piece-512.png")), jPanel2); // NOI18N

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Enter the amount you want to Transfer");

        transferButton.setText("Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter the account number of recipient");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(transferButton))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(transferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(transferAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(transferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(transferButton)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel6, new java.awt.GridBagConstraints());

        TabbedPane.addTab("Transfer", new javax.swing.ImageIcon(getClass().getResource("/407799-200.png")), jPanel3); // NOI18N

        jScrollPane2.setBorder(null);
        jScrollPane2.setToolTipText("");

        MainRegisterPanel.setBackground(new java.awt.Color(204, 204, 204));
        MainRegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterLabel.setFont(new java.awt.Font("Open Sans Extrabold", 0, 14)); // NOI18N
        RegisterLabel.setText("Update Account info");
        MainRegisterPanel.add(RegisterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 69, -1, -1));

        FirstNameLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        FirstNameLabel.setText("First name");
        MainRegisterPanel.add(FirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 113, -1, -1));
        MainRegisterPanel.add(FirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 107, 157, 29));
        MainRegisterPanel.add(LastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 142, 157, 29));

        LastNameTextField.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        LastNameTextField.setText("Last name");
        MainRegisterPanel.add(LastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 148, -1, -1));
        MainRegisterPanel.add(EmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 177, 157, 29));

        EmailAddressLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        EmailAddressLabel.setText("Email Address");
        MainRegisterPanel.add(EmailAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 183, -1, -1));

        PhoneNumberLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        PhoneNumberLabel.setText("Phone Number");
        MainRegisterPanel.add(PhoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 218, -1, -1));
        MainRegisterPanel.add(PhoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 212, 157, 29));

        Password.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Password.setText("Password");
        MainRegisterPanel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 252, -1, -1));

        DOBField.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        DOBField.setText("Date of birth");
        MainRegisterPanel.add(DOBField, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 286, -1, -1));

        DOBTextField.setForeground(Color.GRAY);
        DOBTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBTextFieldFocusLost(evt);
            }
        });
        MainRegisterPanel.add(DOBTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 280, 28, 29));

        RegisterButton.setText("Update");
        RegisterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        MainRegisterPanel.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 94, 33));
        MainRegisterPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 247, 157, 27));

        interestLabel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        interestLabel.setText("Interest-Free");
        MainRegisterPanel.add(interestLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 80, 20));

        yesButton.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        yesButton.setText("Yes");
        MainRegisterPanel.add(yesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        noButton.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        noButton.setText("No");
        MainRegisterPanel.add(noButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        DOBTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBTextField1FocusLost(evt);
            }
        });
        MainRegisterPanel.add(DOBTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 280, 30, 29));

        DOBTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBTextField2FocusLost(evt);
            }
        });
        MainRegisterPanel.add(DOBTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 280, 70, 29));

        jScrollPane2.setViewportView(MainRegisterPanel);

        TabbedPane.addTab("Settings", new javax.swing.ImageIcon(getClass().getResource("/Windows_Settings_app_icon.png")), jScrollPane2); // NOI18N

        Transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Transactions);

        TabbedPane.addTab("Report", new javax.swing.ImageIcon(getClass().getResource("/transact.png")), jScrollPane1); // NOI18N

        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setText("Are you sure you want to logout?");

        LogoutYes.setText("Yes");
        LogoutYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutYesActionPerformed(evt);
            }
        });

        LogoutNo.setText("No");
        LogoutNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(LogoutYes)
                        .addGap(129, 129, 129)
                        .addComponent(LogoutNo)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogoutYes)
                    .addComponent(LogoutNo))
                .addContainerGap(345, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Logout", new javax.swing.ImageIcon(getClass().getResource("/logout.png")), jPanel8); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneMouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed

        int depositval = Integer.parseInt(depositBox.getText());
        if(depositval<=0){
            System.out.println("Error: Deposited amount is less than minimun value");
            return;
        }

        try {
            Customer.Deposit(depositval, null, null, null);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_depositButtonActionPerformed

    private void LogoutYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutYesActionPerformed
        // TODO add your handling code here:
        Login_view lv = new Login_view();
        this.hide();
        lv.setVisible(true);
    }//GEN-LAST:event_LogoutYesActionPerformed

    private void LogoutNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutNoActionPerformed
       // TODO add your handling code here:
       TabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_LogoutNoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int balance = 0;
        try{
            balance = Customer.getBalance();
            System.out.println(balance);
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }
        int withdrawVal = Integer.parseInt(withdrawalBox.getText());
        if(withdrawVal<10){
            System.out.println("Error: Requested withdrawal amount is less than minimun value.");
            return;
        } else if(withdrawVal>balance){
            System.out.println("Error: Requested withdrawal amount is more than your current balance.");
            return;
        }

        try {
            Customer.Withdraw(withdrawVal, null, null, null);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        // TODO add your handling code here:
        int balance = 0;
        try{
            balance = Customer.getBalance();
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }
        int transferVal = Integer.parseInt(transferAmount.getText());
        if(transferVal<10){
            System.out.println("Error: Requested Transfer amount is less than minimun value.");
            return;
        } else if(transferVal>balance){
            System.out.println("Error: Requested Transfer amount is more than your current balance.");
            return;
        }

        try {
            Customer.Transfer(transferVal, null, transferAccountNumber.getText(), null);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_transferButtonActionPerformed

    private void DOBTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextFieldFocusGained
        // TODO add your handling code here:
        DOBTextField.setText("");
        DOBTextField.setForeground(Color.BLACK);
    }//GEN-LAST:event_DOBTextFieldFocusGained

    private void DOBTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextFieldFocusLost
        // TODO add your handling code here:
        if(DOBTextField.getText().isEmpty()){
            DOBTextField.setText("DD");
            DOBTextField.setForeground(Color.GRAY);
        }

    }//GEN-LAST:event_DOBTextFieldFocusLost

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void DOBTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextField1FocusGained
        // TODO add your handling code here:
        DOBTextField1.setText("");
        DOBTextField1.setForeground(Color.BLACK);

    }//GEN-LAST:event_DOBTextField1FocusGained

    private void DOBTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextField1FocusLost
        // TODO add your handling code here:
        if(DOBTextField1.getText().isEmpty()){
            DOBTextField1.setText("MM");
            DOBTextField1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_DOBTextField1FocusLost

    private void DOBTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextField2FocusGained
        // TODO add your handling code here:
        DOBTextField2.setText("");
        DOBTextField2.setForeground(Color.BLACK);
    }//GEN-LAST:event_DOBTextField2FocusGained

    private void DOBTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBTextField2FocusLost
        // TODO add your handling code here:
        if(DOBTextField2.getText().isEmpty()){
            DOBTextField2.setText("YYYY");
            DOBTextField2.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_DOBTextField2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void Main_view(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                try {
                    new Main_view().setVisible(true);
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOBField;
    private javax.swing.JTextField DOBTextField;
    private javax.swing.JTextField DOBTextField1;
    private javax.swing.JTextField DOBTextField2;
    private javax.swing.JLabel EmailAddressLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameLabel;
    private javax.swing.JLabel LastNameTextField;
    private javax.swing.JButton LogoutNo;
    private javax.swing.JButton LogoutYes;
    private javax.swing.JPanel MainRegisterPanel;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTable Transactions;
    private javax.swing.JTextField depositBox;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel interestLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton noButton;
    private javax.swing.JTextField transferAccountNumber;
    private javax.swing.JTextField transferAmount;
    private javax.swing.JButton transferButton;
    private javax.swing.JTextField withdrawalBox;
    private javax.swing.JRadioButton yesButton;
    // End of variables declaration//GEN-END:variables
}
