/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bank.Bank;
import connection.MySql;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Customer;
import models.Manager;
import models.Staff;

/**
 *
 * @author roboto
 */
public class Manager_view extends javax.swing.JFrame {

    private int mousey;
    private int mousex;

    /**
     * Creates new form Manager_view
     */
    public Manager_view() {
        initComponents();
        interest_rate_box.setText(String.valueOf(Bank.getInterestRate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TabbedPane = new javax.swing.JTabbedPane();
        Account_Panel = new javax.swing.JPanel();
        hireStaff = new javax.swing.JPanel();
        firstNamefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LastnameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        Hire = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        fireStaff = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        searchButton = new keeptoo.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        fireButton = new keeptoo.KButton();
        SettingsPanel = new javax.swing.JScrollPane();
        MainRegisterPanel = new javax.swing.JPanel();
        interest_rate_box = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bankNameBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        logoutTab = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        transferButton1 = new keeptoo.KButton();
        transferButton2 = new keeptoo.KButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        TabbedPane.setBackground(new java.awt.Color(82, 82, 82));
        TabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        TabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabbedPane.setToolTipText("");
        TabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabbedPane.setFont(new java.awt.Font("Montserrat Light", 1, 12)); // NOI18N
        TabbedPane.setName(""); // NOI18N
        TabbedPane.setPreferredSize(new java.awt.Dimension(800, 600));
        TabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneStateChanged(evt);
            }
        });
        TabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabbedPaneMouseClicked(evt);
            }
        });

        Account_Panel.setBackground(new java.awt.Color(82, 82, 82));
        Account_Panel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        javax.swing.GroupLayout Account_PanelLayout = new javax.swing.GroupLayout(Account_Panel);
        Account_Panel.setLayout(Account_PanelLayout);
        Account_PanelLayout.setHorizontalGroup(
            Account_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        Account_PanelLayout.setVerticalGroup(
            Account_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Account", new javax.swing.ImageIcon(getClass().getResource("/Users-User-Male-4-icon.png")), Account_Panel); // NOI18N

        hireStaff.setBackground(new java.awt.Color(82, 82, 82));

        firstNamefield.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        firstNamefield.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");

        LastnameField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        LastnameField.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");

        emailField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        emailField.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        Phone.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        Phone.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");

        Username.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        Username.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");

        Password.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");

        Hire.setText("Hire");
        Hire.setkAllowGradient(false);
        Hire.setkAllowTab(false);
        Hire.setkBackGroundColor(new java.awt.Color(202, 62, 71));
        Hire.setkHoverForeGround(new java.awt.Color(202, 62, 71));
        Hire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HireActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hire Staff");

        javax.swing.GroupLayout hireStaffLayout = new javax.swing.GroupLayout(hireStaff);
        hireStaff.setLayout(hireStaffLayout);
        hireStaffLayout.setHorizontalGroup(
            hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hireStaffLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
            .addGroup(hireStaffLayout.createSequentialGroup()
                .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hireStaffLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(hireStaffLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hireStaffLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hireStaffLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hireStaffLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstNamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hireStaffLayout.createSequentialGroup()
                                .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Password, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))))
                    .addGroup(hireStaffLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel8)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        hireStaffLayout.setVerticalGroup(
            hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hireStaffLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(54, 54, 54)
                .addComponent(Hire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Hire Staff", new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/adduser.png"), hireStaff); // NOI18N

        fireStaff.setBackground(new java.awt.Color(82, 82, 82));

        searchField.setBorder(null);

        name.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name");

        searchButton.setText("Search");
        searchButton.setkAllowTab(false);
        searchButton.setkHoverEndColor(new java.awt.Color(202, 62, 71));
        searchButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        searchButton.setkHoverStartColor(new java.awt.Color(202, 62, 71));
        searchButton.setkSelectedColor(new java.awt.Color(202, 62, 71));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(searchTable);

        fireButton.setText("Fire");
        fireButton.setkAllowGradient(false);
        fireButton.setkAllowTab(false);
        fireButton.setkBackGroundColor(new java.awt.Color(202, 62, 71));
        fireButton.setkHoverForeGround(new java.awt.Color(202, 62, 71));
        fireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fireStaffLayout = new javax.swing.GroupLayout(fireStaff);
        fireStaff.setLayout(fireStaffLayout);
        fireStaffLayout.setHorizontalGroup(
            fireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fireStaffLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(fireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fireButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(fireStaffLayout.createSequentialGroup()
                            .addComponent(name)
                            .addGap(36, 36, 36)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        fireStaffLayout.setVerticalGroup(
            fireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fireStaffLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(fireStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fireButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Fire Staff", new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/removeuser.png"), fireStaff); // NOI18N

        SettingsPanel.setBorder(null);
        SettingsPanel.setToolTipText("");

        MainRegisterPanel.setBackground(new java.awt.Color(82, 82, 82));
        MainRegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        interest_rate_box.setBorder(null);
        MainRegisterPanel.add(interest_rate_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 160, 30));

        jLabel1.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Interest rate:");
        MainRegisterPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 165, 110, 20));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MainRegisterPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, 30));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MainRegisterPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, 30));

        bankNameBox.setBorder(null);
        MainRegisterPanel.add(bankNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 160, 30));

        jLabel9.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bank name:");
        MainRegisterPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 100, 30));

        SettingsPanel.setViewportView(MainRegisterPanel);

        TabbedPane.addTab("Settings", new javax.swing.ImageIcon(getClass().getResource("/Windows_Settings_app_icon.png")), SettingsPanel); // NOI18N

        logoutTab.setBackground(new java.awt.Color(82, 82, 82));
        logoutTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutTabMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Montserrat Thin", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Are you sure you want to logout?");

        transferButton1.setBorder(null);
        transferButton1.setText("No");
        transferButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        transferButton1.setkAllowTab(false);
        transferButton1.setkBackGroundColor(new java.awt.Color(202, 62, 71));
        transferButton1.setkEndColor(new java.awt.Color(202, 62, 71));
        transferButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        transferButton1.setkHoverForeGround(new java.awt.Color(202, 62, 71));
        transferButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        transferButton1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        transferButton1.setkStartColor(new java.awt.Color(202, 62, 71));
        transferButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButton1LoginButtonActionPerformed(evt);
            }
        });

        transferButton2.setBorder(null);
        transferButton2.setText("Yes");
        transferButton2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        transferButton2.setkAllowTab(false);
        transferButton2.setkBackGroundColor(new java.awt.Color(202, 62, 71));
        transferButton2.setkEndColor(new java.awt.Color(202, 62, 71));
        transferButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        transferButton2.setkHoverForeGround(new java.awt.Color(202, 62, 71));
        transferButton2.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        transferButton2.setkSelectedColor(new java.awt.Color(255, 255, 255));
        transferButton2.setkStartColor(new java.awt.Color(202, 62, 71));
        transferButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButton2LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoutTabLayout = new javax.swing.GroupLayout(logoutTab);
        logoutTab.setLayout(logoutTabLayout);
        logoutTabLayout.setHorizontalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutTabLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transferButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(transferButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)))
                .addGap(142, 142, 142))
        );
        logoutTabLayout.setVerticalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutTabLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
        );

        TabbedPane.addTab(" Logout", new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/logout.png"), logoutTab); // NOI18N

        jPanel14.setBackground(new java.awt.Color(49, 49, 49));
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel14MouseDragged(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel14MousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Montserrat Thin", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Welcome to Commercial Ethiopian Bank");

        jLabel14.setIcon(new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/close.png")); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transferButton1LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButton1LoginButtonActionPerformed
        TabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_transferButton1LoginButtonActionPerformed

    private void transferButton2LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButton2LoginButtonActionPerformed
        Login_view lv = new Login_view();
        this.hide();
        lv.setVisible(true);
    }//GEN-LAST:event_transferButton2LoginButtonActionPerformed

    private void logoutTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutTabMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutTabMouseClicked

    private void TabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneStateChanged

    private void TabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPaneMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        jLabel14.setIcon(new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/close.png"));
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        jLabel14.setIcon(new javax.swing.ImageIcon("/home/roboto/Documents/AT1/src/close_hover.png"));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(interest_rate_box.getText().isEmpty())
            Bank.showError("Please input before updating value");
        try{
            Float interest_rate = Float.valueOf(interest_rate_box.getText());
            Manager.updateInterests(interest_rate);
        }catch(NumberFormatException E){
            Bank.showError("Please input an apropriate input in the text field");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MousePressed
        // TODO add your handling code here:
                this.mousex = evt.getX();
        this.mousey = evt.getY();

    }//GEN-LAST:event_jPanel14MousePressed

    private void jPanel14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseDragged
        // TODO add your handling code here:        
        this.setLocation(evt.getXOnScreen() - mousex , evt.getYOnScreen() - mousey);


    }//GEN-LAST:event_jPanel14MouseDragged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(bankNameBox.getText().isEmpty())
        {
            Bank.showError("Please Input a new Name");
        }else{
            Manager.updateBankName(bankNameBox.getText());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void HireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HireActionPerformed
        // TODO add your handling code here:
        Manager.addStaff(firstNamefield.getText(), LastnameField.getText(), Phone.getText(), emailField.getText(), Username.getText(), Password.getText());
    }//GEN-LAST:event_HireActionPerformed

    private void fireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireButtonActionPerformed
        // TODO add your handling code here:
        Manager.deleteStaff((int) searchTable.getValueAt(searchTable.getSelectedRow(),0));
    }//GEN-LAST:event_fireButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(searchField.getText().isEmpty())
        {
            Bank.showError("Search string cannot be empty");
        }
        else{
            try {
                Connection conn = MySql.getConnection();
                PreparedStatement ps = conn.prepareStatement("Select staff_id,first_name,last_name,phone,email,role from Staff where first_name like '%"+searchField.getText()+"%' or last_name like '%"+searchField.getText()+"%'");
                ResultSet rs = ps.executeQuery();
                Customer_view.resultSetToTableModel(rs, searchTable);
            } catch (SQLException ex) {
                ex.printStackTrace();
                Bank.showError("SQL Error when searching user");
                
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account_Panel;
    private keeptoo.KButton Hire;
    private javax.swing.JTextField LastnameField;
    private javax.swing.JPanel MainRegisterPanel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JScrollPane SettingsPanel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTextField Username;
    private javax.swing.JTextField bankNameBox;
    private javax.swing.JTextField emailField;
    private keeptoo.KButton fireButton;
    private javax.swing.JPanel fireStaff;
    private javax.swing.JTextField firstNamefield;
    private javax.swing.JPanel hireStaff;
    private javax.swing.JTextField interest_rate_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoutTab;
    private javax.swing.JLabel name;
    private keeptoo.KButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable searchTable;
    private keeptoo.KButton transferButton1;
    private keeptoo.KButton transferButton2;
    // End of variables declaration//GEN-END:variables
}
